import { TITLE } from './lexicon-info';

export const TITLE_FUNCTIONS = {
  'main': function() {return TITLE;},
  'search': function() {return "Search Entries";},
  'betacode': function() {return "Transcription Tables";},
  'entry': function(params) {return params.get('entryToken');},
  'root-group': function(params) {return "Root Group: " + params.get('rootGroup');},
  'compound': function(params) {return "Compound: " + params.get('compound');},
  'semantic-group': function(params) {return "Semantic Group: " + params.get('semGroup');},
  'word-list': function() {return "Word List";},
  'word-list-1letter': function(params) {return "Word List: " + params.get('firstLetter');},
  'word-list-2letter': function(params) {return "Word List: " + params.get('firstLetter') + params.get('secondLetter');},
  'text-view': function(params) {return "Section " + params.get('locationSpec');},
  'about': function() {return "About";},
  'user': function() {return "User Home";},
  'login': function() {return "Access Denied";},
  'access-denied': function() {return "Access Denied";},
  'article-builder': function() {return "Definition Builder";},
  'article-builder-lemma': function(params) {return params.get('lemma') + " Definition Builder";},
  'changelog': function() {return "Change Log";},
  'unwritten-articles': function() {return "Unwritten Articles";},
  'assigned-articles': function() {return "Assigned Articles";},
  'article-drafts': function() {return "Submitted Drafts";},
  'review-entries': function() {return "Review Entries";},
  'user-drafts': function() {return "My Drafts";},
  'article': function(params) {return "View Article " + params.get('id');},
  'reported-issues': function() {return "Reported Issues";},
  'issue': function(params) {return "View Issue " + params.get('id');},
  'report-issue': function() {return "Report an Issue";},
  'inconsistencies': function() {return "Inconsistencies";},
  'inconsistencies-invalid-article-refs': function(params) {return "List of Invalid Article References";},
  'inconsistencies-nonexistent-lemmata': function(params) {return "Lemmata in Text with no Article";},
  'inconsistencies-zero-ref-lemmata': function(params) {return "List of Lemmata not in Text";},
  'manage-lemmata': function() {return "Manage Lemmata";},
  'add-lemma': function() {return "Add Lemma";},
  'edit-lemma': function(params) {return "Edit " + params.get('lemma');},
  'manage-aliases': function() {return "Manage Aliases";},
  'add-alias': function() {return "Add Alias";},
  'edit-alias': function(params) {return "Edit " + params.get('alias');},
  'manage-compound-parts': function() {return "Manage Compound Parts";},
  'add-compound-part': function() {return "Add Compound Part";},
  'edit-compound-part': function(params) {return "Edit " + params.get('compound');},
  'manage-roots': function() {return "Manage Roots";},
  'add-root': function() {return "Add Root";},
  'edit-root': function(params) {return "Edit " + params.get('rootGroup');},
  'manage-semantic-groups': function() {return "Manage Semantic Groups";},
  'add-semantic-group': function() {return "Add Semantic Group";},
  'edit-semantic-group': function(params) {return "Edit " + params.get('semGroup');},
  'manage-text': function() {return "Manage Text";},
  'edit-text': function(params) {return "Edit Text " + params.get('location');},
  'edit-token': function(params) {return "Edit Token " + params.get('tokenIndex');},
  'lemma-meanings': function(params) {return "Edit Meaning Links for " + params.get('lemma');},
  'recompile-texts': function() {return "Recompile Text";},
  'backups-overview': function() {return "Backups Overview";},
  'export': function() {return "Export Lexicon";},
  '404': function() {return "Page Not Found";},
}
